apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: involved-tyrannosaurus-go 
  janus-idp.io/tekton: involved-tyrannosaurus-go
  backstage.io/kubernetes-id: involved-tyrannosaurus-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: involved-tyrannosaurus-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  